// AUTH
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_SIGN_IN_ERROR = 'AUTH_SIGN_IN_ERROR';
export const AUTH_SIGN_UP_ERROR = 'AUTH_SIGN_UP_ERROR';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_CHANGED_AVATAR = 'AUTH_CHANGED_AVATAR';
export const AUTH_CHANGED_AVATAR_ERROR = 'AUTH_CHANGED_AVATAR';
export const AUTH_CHANGED_PASSWORD = 'AUTH_CHANGED_PASSWORD';
export const AUTH_CHANGED_PASSWORD_ERROR = 'AUTH_CHANGED_PASSWORD_ERROR';
export const TOKEN_ACCESS = 'TOKEN_ACCESS';
export const TOKEN_ERROR = 'TOKEN_ERROR';
export const CLEAR_FETCH_MESSAGE = 'CLEAR_FETCH_MESSAGE';

// CHAT 
export const GET_ROOMS = 'GET_ROOMS';
export const NEW_ROOM = 'NEW_ROOM';
export const CHANGE_ROOM = 'CHANGE_ROOM';
export const JOIN_ROOM = 'JOIN_ROOM';
export const DELETE_ROOM = 'DELETE_ROOM';
export const GET_MESSAGES = 'GET_MESSAGES';
export const NEW_CHANNEL = 'NEW_CHANNEL';
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';
export const CHANGE_CHANNEL_SETTINGS = 'CHANGE_CHANNEL_SETTINGS'
export const CHANGE_CHANNEL_SETTINGS_ERROR = 'CHANGE_CHANNEL_ERROR'

export const SHOW_ROOM_OPTIONS = 'SHOW_ROOM_OPTIONS';